[build]
  command = "npm run build"  # Adjust this to match your build command for the React app
  functions = "netlify/functions"  # If you have serverless functions
  publish = "build"  # The directory where your built React app is located

[[redirects]]  # This configuration is typically used for single-page applications like React
  from = "/*"
  to = "/index.html"
  status = 200

# (optional) Settings for Netlify Dev
#[dev]
#  command = "yarn start"  # Command to start your dev server (if using Netlify Dev)
#  port = 3000  # Port that the dev server will be listening on
#  publish = "dist"  # Folder with the static content for _redirect file

